Booksotre_static_MVC/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Booksotre_static_MVC.Models
{
    public enum Genre
    {
        Science,
        Comedy,
        Horror
    }

    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public Genre genre { get; set; }
        public bool Deleted { get; set; }

        public Book(int Id, string Name, decimal Price, Genre genre, bool Deleted)
        {
            this.Id = Id;
            this.Name = Name;
            this.Price = Price;
            this.genre = genre;
            this.Deleted = Deleted;
        }
    }
}

Booksotre_static_MVC/Models/Bookstore.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Booksotre_static_MVC.Models
{
    public class Bookstore
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Book> Books { get; set; }

        public Bookstore(int Id, string Name)
        {
            this.Id = Id;
            this.Name = Name;
            this.Books = new List<Book>();
        }
    }
}

Booksotre_static_MVC/Controllers/BookstoresController.cs
using Booksotre_static_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Booksotre_static_MVC.Controllers
{
    public class BookstoresController : Controller
    {
        private static Bookstore bookstore;

        static BookstoresController()
        {
            bookstore = new Bookstore(1, "Vulkan");

            Book book1 = new Book(1, "Snesko", 1000m, Genre.Horror, false);
            Book book2 = new Book(2, "Sicilijanac", 2100m, Genre.Science, false);
            Book book3 = new Book(3, "Komsija", 899m, Genre.Comedy, false);

            bookstore.Books.Add(book1);
            bookstore.Books.Add(book2);
            bookstore.Books.Add(book3);
        }
        // GET: Bookstores
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddNew(string Name, decimal Price, Genre genre)
        {
            Book b = new Book(bookstore.Books.Count + 1, Name, Price, genre, false);
            bookstore.Books.Add(b);
            return RedirectToAction("List");
        }

        public ActionResult List()
        {
            ViewBag.books = bookstore.Books.Where(x => x.Deleted != true);
            return View();
        }

        public ActionResult Deleted()
        {
            ViewBag.deletedBooks = bookstore.Books.Where(x => x.Deleted == true);

            return View();
        }

        public ActionResult Delete(int id)
        {
            foreach(Book b in bookstore.Books)
            {
                if(b.Id == id)
                {
                    b.Deleted = true;
                }
            }
            return RedirectToAction("List");
        }

        public ActionResult Sort()
        {
            return View();
        }
        public ActionResult SortResult(int sortBy, int order)
        {
            if(sortBy == 1 && order == 1)
            {
                ViewBag.books = bookstore.Books.Where(x => x.Deleted == false).OrderBy(x => x.Price);
            }
            else if(sortBy == 1 && order == 2)
            {
                ViewBag.books = bookstore.Books.Where(x => x.Deleted == false).OrderByDescending(x => x.Price);
            }
            else if(sortBy == 2 && order == 1)
            {
                ViewBag.books = bookstore.Books.Where(x => x.Deleted == false).OrderBy(x => x.Name);
            }
            else
            {
                ViewBag.books = bookstore.Books.Where(x => x.Deleted == false).OrderByDescending(x => x.Name);
            }
            return View();
        }
    }
}

Booksotre_static_MVC/Views/Bookstores/Deleted.cshtml
@{
    ViewBag.Title = "Deleted";
}

<h2>Deleted</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Genre</th>
            <th></th>
        </tr>
    </thead>
    @foreach(var b in ViewBag.deletedBooks)
    {
        <tr>
            <td>@b.Id</td>
            <td>@b.Name</td>
            <td>@b.Price</td>
            <td>@b.genre</td>
            <td><a href="#">Details</a></td>
        </tr>
    }
</table>
<a href="/Bookstores/Index/">Link for homepage</a>

Booksotre_static_MVC/Views/Bookstores/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Add new book</h2>

<form action="/Bookstores/AddNew" method="post">
    <div class="form-group">
        <label for="Name">Name of book</label>
        <input type="text" name="Name" class="form-control"/>
    </div>
    <div class="form-group">
        <label for="Price">Price of book</label>
        <input type="number" name="Price" class="form-control"/>
    </div>
    <label for="genre">Genre of book</label>
        <select name="genre">
            <option value="1">Science</option>
            <option value="2">Comedy</option>
            <option value="3">Horror</option>
        </select>
    <br />
    <input type="submit" value="Add new" class="btn btn-sm btn-success"/>
</form>
<a href="/Bookstores/List">Show all books</a> | <a href="/Bookstores/Deleted">Show deleted books</a>

Booksotre_static_MVC/Views/Bookstores/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<table class="table table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Genre</th>
            <th></th>
            <th></th>
        </tr>
    </thead>

    @foreach (var b in ViewBag.books)
    {
        <tr>
            <td>@b.Id</td>
            <td>@b.Name</td>
            <td>@b.Price</td>
            <td>@b.genre</td>
            <td><a href="/Bookstores/Delete?id=@b.Id">Delete</a></td>
            <td><a href="#">Details</a></td>
        </tr>
    }

</table>
<a href="/Bookstores/Index/">Link for homepage</a>

Booksotre_static_MVC/Views/Bookstores/Sort.cshtml
@{
    ViewBag.Title = "Sort";
}

<h2>Sort</h2>

<form action="/Bookstores/SortResult" method="get">
    <label for="sortBy">Sort by</label>
    <select name="sortBy">
        <option value="1">Price</option>
        <option value="2">Name</option>
    </select>
    <label for="order">Order</label>
    <select name="order">
        <option value="1">Ascending</option>
        <option value="2">Descending</option>
    </select>
    <button type="submit" class="btn btn-sm btn-warning">Sort</button>
</form>

Booksotre_static_MVC/Views/Bookstores/SortResult.cshtml
@{
    ViewBag.Title = "SortResult";
}

<h2>Sort Result</h2>

<table class="table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Price</th>
            <th>Genre</th>
        </tr>
    </thead>

    @foreach(var b in ViewBag.books)
    {
        <tr>
            <td>@b.Id</td>
            <td>@b.Name</td>
            <td>@b.Price</td>
            <td>@b.genre</td>
        </tr>
    }
</table>

Booksotre_static_MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Booksotre_static_MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Booksotre_static_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Booksotre_static_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bookstore","Index", "Bookstores", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Bookstores")</li>
                    <li>@Html.ActionLink("Sort", "Sort", "Bookstores")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>